### ISSUE TITLE
Installation manual

### ISSUE THREAD

**Issue by sualko** [Weissheiten/Weissheiten.Neos.Bootstrap#3]
Sorry, I am a newbie to Neos 2.0 and need some help to setup your great plugin.

I followed option 2 from [typo3.org](https://buzz.typo3.org/people/florian-weiss/article/let-me-see-you-bootstrapped/) and now your package is inside of <code>Packages/Sites/MYSITE/Packages/Application/</code>, but now how can I use it? It does not show app in the Package Management and also not in the "Create New" dialog.

I tried <code>./flow flow:cache:flush --force</code> and <code>./flow typo3.typo3cr:node:repair</code>.

Please give me some advice.

**Comment by Weissheiten** [comment]
Hi sualko,
the package should reside in: Packages/Application directly as Packages are shared among sites
You might want to sign up to http://neos-project.slack.com as the community usually is in there (also to help out people new to Neos)

**Comment by sualko** [comment]
> the package should reside in: Packages/Application directly

But how does this work, if I want to share my site as a template? 

> You might want to sign up to http://neos-project.slack.com

Seems to me as I need an <code>@neos.io</code> email to sign in.

**Comment by sualko** [comment]
I think https://discuss.neos.io/ is the right place to ask noob questions. Nonetheless a quick start manual would be great for your package. Maybe if I got it running, I will create a pull request.

**Comment by Weissheiten** [comment]
great, thank you. I'll try to incorporate this along with the update for Neos 2.0 as soon as I find the time (could take a bit due to workload atm though)

**Comment by sualko** [comment]
If I got you right, this package does currently not work for Neos 2.0?

**Comment by Weissheiten** [comment]
Most of it does, if I remember correctly the orbit slider needs a small tweak

**Comment by egobude** [comment]
I already did a few changes for Neos 2 :) 

https://github.com/egobude/Weissheiten.Neos.Bootstrap/commit/327ba3508ae863ad424329c308791a2babac3424

PR is comming soon :)

**Comment by egobude** [comment]
@see: https://github.com/Weissheiten/Weissheiten.Neos.Bootstrap/pull/4

**Comment by sualko** [comment]
I think #4 fixes this issue. Thanks for your work, guys.
